/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-11-04 06:08:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.course;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class courseList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>여행 코스 목록보기</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/course/courseList.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<section>\r\n");
      out.write("\t<div id=\"all_div\">\r\n");
      out.write("\t\t<div id=\"menu_div\">\r\n");
      out.write("\t\t\t<div id=\"menu_left_div\">\r\n");
      out.write("\t\t\t\t<img src=\"resources/images/courseIcon.png\" id=\"menu_img\"/>\r\n");
      out.write("\t\t\t\t<span id=\"menu\">여행 코스</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"menu_right_div\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"input_search\"/>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"검색\" id=\"button_search\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"cate_table_div\">\r\n");
      out.write("\t\t\t<b>지역</b>\r\n");
      out.write("\t\t\t<table id=\"local_table\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>전체</td>\r\n");
      out.write("\t\t\t\t\t<td>서울</td>\r\n");
      out.write("\t\t\t\t\t<td>인천</td>\r\n");
      out.write("\t\t\t\t\t<td>대전</td>\r\n");
      out.write("\t\t\t\t\t<td>대구</td>\r\n");
      out.write("\t\t\t\t\t<td>광주</td>\r\n");
      out.write("\t\t\t\t\t<td>부산</td>\r\n");
      out.write("\t\t\t\t\t<td>울산</td>\r\n");
      out.write("\t\t\t\t\t<td>세종</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>경기</td>\r\n");
      out.write("\t\t\t\t\t<td>강원</td>\r\n");
      out.write("\t\t\t\t\t<td>충북</td>\r\n");
      out.write("\t\t\t\t\t<td>충남</td>\r\n");
      out.write("\t\t\t\t\t<td>경북</td>\r\n");
      out.write("\t\t\t\t\t<td>경남</td>\r\n");
      out.write("\t\t\t\t\t<td>전북</td>\r\n");
      out.write("\t\t\t\t\t<td>전남</td>\r\n");
      out.write("\t\t\t\t\t<td>제주</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<b>테마</b>\r\n");
      out.write("\t\t\t<table id=\"theme_table\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>전체</td>\r\n");
      out.write("\t\t\t\t\t<td>가족 여행</td>\r\n");
      out.write("\t\t\t\t\t<td>나 홀로 여행</td>\r\n");
      out.write("\t\t\t\t\t<td>커플 여행</td>\r\n");
      out.write("\t\t\t\t\t<td>친구와 함께</td>\r\n");
      out.write("\t\t\t\t\t<td>뚜벅이 코스</td>\r\n");
      out.write("\t\t\t\t\t<td>캠핑</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<b>일정</b>\r\n");
      out.write("\t\t\t<table id=\"calendar_table\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>전체</td>\r\n");
      out.write("\t\t\t\t\t<td>당일 여행</td>\r\n");
      out.write("\t\t\t\t\t<td>1박2일</td>\r\n");
      out.write("\t\t\t\t\t<td>2박3일 이상</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"list_all_div\">\r\n");
      out.write("\t\t\t<div id=\"list_count_div\">\r\n");
      out.write("\t\t\t\t총<span id=\"list_count\">76</span>건\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 코스마다마다의 div -->\r\n");
      out.write("\t\t\t<div id=\"list_course_div\">\r\n");
      out.write("\t\t\t\t<div id=\"course_img_div\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/travel.PNG\" id=\"travel_img\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"course_name_writer_div\">\r\n");
      out.write("\t\t\t\t\t<div id=\"course_name\">코스 이름</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"course_writer\">뿌슝빠슝</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"course_cate_tag_div\">\r\n");
      out.write("\t\t\t\t\t<div id=\"course_cate\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"course_local\">대구 중구</span>\r\n");
      out.write("\t\t\t\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"course_theme\">가족 여행</span>\r\n");
      out.write("\t\t\t\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"course_calendar\">1박2일</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"course_tag\">\r\n");
      out.write("\t\t\t\t\t\t#공예품라라라<br>\r\n");
      out.write("\t\t\t\t\t\t#가족들과함께<br>\r\n");
      out.write("\t\t\t\t\t\t#룰루사천여행\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"list_course_div\">\r\n");
      out.write("\t\t\t\t<div id=\"course_img_div\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/travel.PNG\" id=\"travel_img\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"course_name_writer_div\">\r\n");
      out.write("\t\t\t\t\t<div id=\"course_name\">코스 이름</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"course_writer\">뿌슝빠슝</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"course_cate_tag_div\">\r\n");
      out.write("\t\t\t\t\t<div id=\"course_cate\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"course_local\">대구 중구</span>\r\n");
      out.write("\t\t\t\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"course_theme\">가족 여행</span>\r\n");
      out.write("\t\t\t\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"course_calendar\">1박2일</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"course_tag\">\r\n");
      out.write("\t\t\t\t\t\t#공예품라라라<br>\r\n");
      out.write("\t\t\t\t\t\t#가족들과함께<br>\r\n");
      out.write("\t\t\t\t\t\t#룰루사천여행\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"list_course_div\">\r\n");
      out.write("\t\t\t\t<div id=\"course_img_div\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/travel.PNG\" id=\"travel_img\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"course_name_writer_div\">\r\n");
      out.write("\t\t\t\t\t<div id=\"course_name\">코스 이름</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"course_writer\">뿌슝빠슝</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"course_cate_tag_div\">\r\n");
      out.write("\t\t\t\t\t<div id=\"course_cate\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"course_local\">대구 중구</span>\r\n");
      out.write("\t\t\t\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"course_theme\">가족 여행</span>\r\n");
      out.write("\t\t\t\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"course_calendar\">1박2일</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"course_tag\">\r\n");
      out.write("\t\t\t\t\t\t#공예품라라라<br>\r\n");
      out.write("\t\t\t\t\t\t#가족들과함께<br>\r\n");
      out.write("\t\t\t\t\t\t#룰루사천여행\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"button_write_div\">\r\n");
      out.write("\t\t\t<button id=\"button_write\">등록하기</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"paging_div\">\r\n");
      out.write("\t\t\t<button id=\"before\">&lt;</button>\r\n");
      out.write("\t\t\t<button id=\"current\">1</button>\r\n");
      out.write("\t\t\t<button class=\"num\">2</button>\r\n");
      out.write("\t\t\t<button class=\"num\">3</button>\r\n");
      out.write("\t\t\t<button id=\"after\">&gt;</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
