/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-11-04 06:10:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.hotel;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hotel_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1604145899265L));
    _jspx_dependants.put("jar:file:/C:/Users/Joy/git/Spring-Project-Trip2Reap/Spring-Final-Trip2Reap/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("    <!-- jquery -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- css -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/hotel/hotel_list.css\">\n");
      out.write("\n");
      out.write("    <!-- font-awesome -->\n");
      out.write("    <script src=\"https://kit.fontawesome.com/09697e2134.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <title>호텔 페이지</title>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div>\n");
      out.write("   \t \t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("    <div id=\"main-container\">\n");
      out.write("    \n");
      out.write("    \t\n");
      out.write("    \n");
      out.write("        <div id=\"title-container\">\n");
      out.write("            <img id=\"hotel-icon\" src=\"resources/images/hotel.png\">\n");
      out.write("            <span id=\"title-name\">호텔 예약</span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div id=\"button-container\">\n");
      out.write("            <div id=\"left_btns_container\">\n");
      out.write("                <ul id=\"left_btns\" class=\"btn_ul\">\n");
      out.write("                \t<!-- 호텔등록은 관리자 회원만 가능하다! / 관리자인지 확인하는 방법을 모색해보자. -->\n");
      out.write("                \t");
      out.write("\n");
      out.write("                    <li><button id=\"insert-hotel\" class=\"btn\" onclick=\"location.href='hotelInsertView.ho'\">호텔 등록하기</button></li>\n");
      out.write("                    <li><button id=\"detail-search\" class=\"btn\">상세검색</button></li>\n");
      out.write("                </ul>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div></div>\n");
      out.write("\n");
      out.write("            <div id=\"right_btns_container\">\n");
      out.write("                <ul id=\"right_btns\" class=\"btn_ul\">\n");
      out.write("                    <li><button class=\"btn\">인기순</button></li>\n");
      out.write("                    <li><button class=\"btn\">가격순</button></li>\n");
      out.write("                    <li><button class=\"btn\">등록순</button></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div id=\"hotel-list-container\">\n");
      out.write("\n");
      out.write("\t\t\t");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- 호텔 1개(샘플1) -->\n");
      out.write("            <div class=\"one-hotel-info-container\">\n");
      out.write("                <img src=\"resources/images/sample_hotel.jpg\" alt=\"호텔이미지\">\n");
      out.write("\n");
      out.write("                <div class=\"detail-info-container\">\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"info-container\">\n");
      out.write("                            <!-- 호텔이름 -->\n");
      out.write("                            <div class=\"hotel-name-container\">\n");
      out.write("                                <h1>호텔 델루나{호텔이름}</h1>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- 좋아요 버튼 -->\n");
      out.write("                            <div class=\"i-like-btn-container\">\n");
      out.write("                                <i class=\"fas fa-heart unlike\"></i>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <hr>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"detail-info-wrapper\">\n");
      out.write("                        <!-- 호텔주소 -->\n");
      out.write("                        <div class=\"hotel-addr-wrapper\">\n");
      out.write("                            <small>{호텔주소}</small>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <div class=\"hotel-info-wrapper\">\n");
      out.write("                            <!-- 별점 -->\n");
      out.write("                            <div class=\"hotel-review-container\">\n");
      out.write("                                <span class=\"star-point\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star-half-alt\"></i>\n");
      out.write("                                    <i class=\"far fa-star\"></i>\n");
      out.write("                                    <i class=\"far fa-star\"></i>\n");
      out.write("                                </span>\n");
      out.write("                                <span> 2.54 / 5 </span>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <hr>\n");
      out.write("                            <!-- 1박 가격 -->\n");
      out.write("                            <div class=\"hotel-per-day-price-container info-container\">\n");
      out.write("                                <p>\n");
      out.write("                                    <small>1박 중</small>&nbsp;&nbsp;<b>47,216원</b>\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <button class=\"hotel-reserve-btn\">예약하기</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- 호텔1개(샘플1) 끝-->\n");
      out.write("\n");
      out.write("            <!-- 호텔 1개(샘플2) -->\n");
      out.write("            <div class=\"one-hotel-info-container\">\n");
      out.write("                <img src=\"resources/images/trump.jpeg\" alt=\"호텔이미지\">\n");
      out.write("\n");
      out.write("                <div class=\"detail-info-container\">\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"info-container\">\n");
      out.write("                            <!-- 호텔이름 -->\n");
      out.write("                            <div class=\"hotel-name-container\">\n");
      out.write("                                <h1>호텔 트럼프</h1>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- 좋아요 버튼 -->\n");
      out.write("                            <div class=\"i-like-btn-container\">\n");
      out.write("                                <i class=\"fas fa-heart unlike\"></i>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <hr>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"detail-info-wrapper\">\n");
      out.write("                        <!-- 호텔주소 -->\n");
      out.write("                        <div class=\"hotel-addr-wrapper\">\n");
      out.write("                            <small>미국 라스베가스 trump 거리</small>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <div class=\"hotel-info-wrapper\">\n");
      out.write("                            <!-- 별점 -->\n");
      out.write("                            <div class=\"hotel-review-container\">\n");
      out.write("                                <span class=\"star-point\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"far fa-star\"></i>\n");
      out.write("                                    <i class=\"far fa-star\"></i>\n");
      out.write("                                </span>\n");
      out.write("                                <span> 3.0 / 5 </span>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <hr>\n");
      out.write("                            <!-- 1박 가격 -->\n");
      out.write("                            <div class=\"hotel-per-day-price-container info-container\">\n");
      out.write("                                <p>\n");
      out.write("                                    <small>1박 중</small>&nbsp;&nbsp;<b>47,216원</b>\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <button class=\"hotel-reserve-btn\">예약하기</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- 호텔 1개(샘플2) 끝 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- 호텔 1개(샘플3) 시작 -->\n");
      out.write("            <div class=\"one-hotel-info-container\">\n");
      out.write("                <img src=\"resources/images/sinra.jpeg\" alt=\"호텔이미지\">\n");
      out.write("\n");
      out.write("                <div class=\"detail-info-container\">\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"info-container\">\n");
      out.write("                            <!-- 호텔이름 -->\n");
      out.write("                            <div class=\"hotel-name-container\">\n");
      out.write("                                <h1>신라호텔</h1>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- 좋아요 버튼 -->\n");
      out.write("                            <div class=\"i-like-btn-container\">\n");
      out.write("                                <i class=\"fas fa-heart unlike\"></i>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <hr>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"detail-info-wrapper\">\n");
      out.write("                        <!-- 호텔주소 -->\n");
      out.write("                        <div class=\"hotel-addr-wrapper\">\n");
      out.write("                            <small>서울특별시 중구 장충동 동호로249</small>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <div class=\"hotel-info-wrapper\">\n");
      out.write("                            <!-- 별점 -->\n");
      out.write("                            <div class=\"hotel-review-container\">\n");
      out.write("                                <span class=\"star-point\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"far fa-star\"></i>\n");
      out.write("                                    <i class=\"far fa-star\"></i>\n");
      out.write("                                </span>\n");
      out.write("                                <span> 3.0 / 5 </span>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <hr>\n");
      out.write("                            <!-- 1박 가격 -->\n");
      out.write("                            <div class=\"hotel-per-day-price-container info-container\">\n");
      out.write("                                <p>\n");
      out.write("                                    <small>1박 중</small>&nbsp;&nbsp;<b>47,216원</b>\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <button class=\"hotel-reserve-btn\">예약하기</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- 호텔 1개(샘플3) 끝 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- 호텔1개 (샘플4) 시작 -->\n");
      out.write("            <div class=\"one-hotel-info-container\">\n");
      out.write("                <img src=\"resources/images/sinra.jpeg\" alt=\"호텔이미지\">\n");
      out.write("\n");
      out.write("                <div class=\"detail-info-container\">\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"info-container\">\n");
      out.write("                            <!-- 호텔이름 -->\n");
      out.write("                            <div class=\"hotel-name-container\">\n");
      out.write("                                <h1>신라호텔</h1>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- 좋아요 버튼 -->\n");
      out.write("                            <div class=\"i-like-btn-container\">\n");
      out.write("                                <i class=\"fas fa-heart unlike\"></i>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <hr>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"detail-info-wrapper\">\n");
      out.write("                        <!-- 호텔주소 -->\n");
      out.write("                        <div class=\"hotel-addr-wrapper\">\n");
      out.write("                            <small>서울특별시 중구 장충동 동호로249</small>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <div class=\"hotel-info-wrapper\">\n");
      out.write("                            <!-- 별점 -->\n");
      out.write("                            <div class=\"hotel-review-container\">\n");
      out.write("                                <span class=\"star-point\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"far fa-star\"></i>\n");
      out.write("                                    <i class=\"far fa-star\"></i>\n");
      out.write("                                </span>\n");
      out.write("                                <span> 3.0 / 5 </span>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <hr>\n");
      out.write("                            <!-- 1박 가격 -->\n");
      out.write("                            <div class=\"hotel-per-day-price-container info-container\">\n");
      out.write("                                <p>\n");
      out.write("                                    <small>1박 중</small>&nbsp;&nbsp;<b>47,216원</b>\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <button class=\"hotel-reserve-btn\">예약하기</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- 호텔1개(샘플4) 끝 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- 호텔 1개(샘플5) 시작 -->\n");
      out.write("            <div class=\"one-hotel-info-container\">\n");
      out.write("                <img src=\"resources/images/sinra.jpeg\" alt=\"호텔이미지\">\n");
      out.write("\n");
      out.write("                <div class=\"detail-info-container\">\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"info-container\">\n");
      out.write("                            <!-- 호텔이름 -->\n");
      out.write("                            <div class=\"hotel-name-container\">\n");
      out.write("                                <h1>신라호텔</h1>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- 좋아요 버튼 -->\n");
      out.write("                            <div class=\"i-like-btn-container\">\n");
      out.write("                                <i class=\"fas fa-heart unlike\"></i>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <hr>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"detail-info-wrapper\">\n");
      out.write("                        <!-- 호텔주소 -->\n");
      out.write("                        <div class=\"hotel-addr-wrapper\">\n");
      out.write("                            <small>서울특별시 중구 장충동 동호로249</small>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <div class=\"hotel-info-wrapper\">\n");
      out.write("                            <!-- 별점 -->\n");
      out.write("                            <div class=\"hotel-review-container\">\n");
      out.write("                                <span class=\"star-point\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"far fa-star\"></i>\n");
      out.write("                                    <i class=\"far fa-star\"></i>\n");
      out.write("                                </span>\n");
      out.write("                                <span> 3.0 / 5 </span>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <hr>\n");
      out.write("                            <!-- 1박 가격 -->\n");
      out.write("                            <div class=\"hotel-per-day-price-container info-container\">\n");
      out.write("                                <p>\n");
      out.write("                                    <small>1박 중</small>&nbsp;&nbsp;<b>47,216원</b>\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <button class=\"hotel-reserve-btn\">예약하기</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- 호텔1개(샘플5) 끝 -->\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!--호텔리스트 끝  -->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- 호텔페이지네이션 시작 -->\n");
      out.write("        <div id=\"pagination-container\">\n");
      out.write("        \t<nav>\n");
      out.write("                <ul id=\"pagination-ul\">\n");
      out.write("\n");
      out.write("                    <!-- 맨앞으로 -->\n");
      out.write("                    <li><a href=\"\">&lt;&lt;</a></li>\n");
      out.write("\n");
      out.write("                    <!-- 이전페이지 -->\n");
      out.write("                    <li><a href=\"\">&lt;</a></li>\n");
      out.write("\n");
      out.write("                    <!-- 페이지번호 -->\n");
      out.write("                    <li><a href=\"\">1</a></li>\n");
      out.write("                    <li><a href=\"\">2</a></li>\n");
      out.write("                    <li><a href=\"\">3</a></li>\n");
      out.write("                    <li><a href=\"\">4</a></li>\n");
      out.write("                    <li><a href=\"\">5</a></li>\n");
      out.write("\n");
      out.write("                    <!-- 이후페이지 -->\n");
      out.write("                    <li><a href=\"\">&gt;</a></li>\n");
      out.write("                    <!-- 맨뒤로 이동 -->\n");
      out.write("                    <li><a href=\"\">&gt;&gt;</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("        </div>\n");
      out.write("        <!-- 호텔페이지네이션 끝 -->\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- modal-->\n");
      out.write("    <div id=\"modal-container\">\n");
      out.write("        <div id=\"modal-background\" class=\"modal-background\">\n");
      out.write("            <div class=\"modal\">\n");
      out.write("\n");
      out.write("                <div class=\"close-modal-container\">\n");
      out.write("                    <div></div>\n");
      out.write("                    <div>\n");
      out.write("                        <i id=\"close_btn\" class=\"fas fa-times\"></i>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"modal-title-container\">\n");
      out.write("                    <h2>상세검색</h2>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"modal-body-container\">\n");
      out.write("                    <table >\n");
      out.write("                        <tr colspan=3>\n");
      out.write("                            <td>\n");
      out.write("                                <h5>지역검색</h5>\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <select class=\"detail-search-option\" name=\"place\" id=\"place\">\n");
      out.write("                                    <option value=\"\">지역선택</option>\n");
      out.write("                                    <option value=\"강원도\">강원도</option>\n");
      out.write("                                    <option value=\"경기도\">경기도</option>\n");
      out.write("                                    <option value=\"경상남도\">경상남도</option>\n");
      out.write("                                    <option value=\"경상북도\">경상북도</option>\n");
      out.write("                                    <option value=\"광주광역시\">광주광역시</option>\n");
      out.write("                                    <option value=\"대구광역시\">대구광역시</option>\n");
      out.write("                                    <option value=\"대전광역시\">대전광역시</option>\n");
      out.write("                                    <option value=\"부산광역시\">부산광역시</option>\n");
      out.write("                                    <option value=\"서울특별시\">서울특별시</option>\n");
      out.write("                                    <option value=\"세종특별자치시\">세종특별자치시</option>\n");
      out.write("                                    <option value=\"인천광역시\">인천광역시</option>\n");
      out.write("                                    <option value=\"울산광역시\">울산광역시</option>\n");
      out.write("                                    <option value=\"전라북도\">전라북도</option>\n");
      out.write("                                    <option value=\"전라남도\">전라남도</option>\n");
      out.write("                                    <option value=\"제주특별자치도\">제주특별자치도</option>\n");
      out.write("                                    <option value=\"충청북도\">충청북도</option>\n");
      out.write("                                    <option value=\"충청남도\">충청남도</option>\n");
      out.write("                                </select>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>\n");
      out.write("                                <h5>호텔등급</h5>\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <select class=\"detail-search-option\" name=\"rank\" id=\"rank\">\n");
      out.write("                                    <option value=\"\">등급 선택</option>\n");
      out.write("                                    <option value=\"1\">1</option>\n");
      out.write("                                    <option value=\"2\">2</option>\n");
      out.write("                                    <option value=\"3\">3</option>\n");
      out.write("                                    <option value=\"4\">4</option>\n");
      out.write("                                    <option value=\"5\">5</option>\n");
      out.write("                                </select>\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>\n");
      out.write("                                <h5>가격대 </h5>\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <select class=\"detail-search-option\" name=\"price-per-day\" id=\"price-per-day\">\n");
      out.write("                                    <option value=\"\">가격 선택</option>\n");
      out.write("                                    <option value=\"5만원 미만\">5만원 미만</option>\n");
      out.write("                                    <option value=\"10만원 미만\">5만원 이상 ~ 10만원 미만</option>\n");
      out.write("                                    <option value=\"15만원 미만\">10만원 이상 ~ 15만원 미만</option>\n");
      out.write("                                    <option value=\"20만원 미만\">15만원 이상 ~ 20만원 미만</option>\n");
      out.write("                                    <option value=\"20만원 이상\">20만원 이상</option>\n");
      out.write("                                </select>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>\n");
      out.write("                                <h5>호텔이름</h5>\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <input class=\"detail-search-option\" name=\"hotel-name\" id=\"hotel-name\" type=\"text\">\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"modal-btn-container\">\n");
      out.write("                    <button id=\"detail-hotel-search\">호텔 검색</button>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- modal끝 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("//heart -btn\n");
      out.write("$(function(){\n");
      out.write("\tlet heart_btns= document.querySelectorAll('.fa-heart');\n");
      out.write("\theart_btns.forEach(function(heart_btn){\n");
      out.write("\t\theart_btn.onclick=function(){\n");
      out.write("\t\t\t//unlike 라는 이름의 클래스를 가지고있다.\n");
      out.write("\t\t\tif( heart_btn.classList.contains('unlike') ){\n");
      out.write("\t\t\t\tconsole.log('좋아요!');\n");
      out.write("\t\t\t\tthis.classList.toggle('like');\n");
      out.write("\t\t\t\tthis.classList.remove('unlike');\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t//ajax요청해서 해당 호텔 좋아요 수 +1카운트...^^;\n");
      out.write("\t\t\t\t//그런데 일단은 로그인을 한 상태에만 가능하다는것 !!\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}else if(heart_btn.classList.contains('like')){\n");
      out.write("\t\t\t\tconsole.log('좋아요 해제');\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tthis.classList.toggle('unlike');\n");
      out.write("\t\t\t\t//this.classList.remove('like');\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("}); //smash-heart-btn wrapper finised\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("// modal\n");
      out.write("$(function(){\n");
      out.write("        var $detailSearchBtn=$('#detail-search'),\n");
      out.write("        $modalContainer = $('#modal-container'),\n");
      out.write("        $body = $('body'),\n");
      out.write("        $content= $('#main-container'),\n");
      out.write("        $closeBtn= $('#close_btn'),\n");
      out.write("        $btnId;\n");
      out.write("\n");
      out.write("        // 상세검색 버튼을 클릭.\n");
      out.write("        $detailSearchBtn.on('click', function(){\n");
      out.write("            //버튼아이디를 불러옵니다.\n");
      out.write("            $btnId= $(this).attr('id'); //detail-search \n");
      out.write("            \n");
      out.write("            //modal-container에 기존 클래스들을 빼놓고, btnId클래스를 적용합니다.\n");
      out.write("            $modalContainer\n");
      out.write("                .removeAttr('class')\n");
      out.write("                .addClass($btnId);\n");
      out.write("\n");
      out.write("            $content\n");
      out.write("                .removeAttr('class')\n");
      out.write("                .addClass('content');\n");
      out.write("\n");
      out.write("            $body.addClass('modal-active'); //body에 modal-active라는 클래스를 적용.\n");
      out.write("            \n");
      out.write("            $content.addClass($btnId);\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        //닫기버튼(x 표시 아이콘) 클릭시\n");
      out.write("        $closeBtn.on('click', function(){\n");
      out.write("            $modalContainer.addClass('out');\n");
      out.write("            $body.removeClass('modal-active'); //modal-active 클래스 해제\n");
      out.write("        \n");
      out.write("            if($modalContainer.hasClass($btnId)){\n");
      out.write("                $content.addClass('out');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("}); //modal- wrapper finished\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("\t\n");
      out.write("    \n");
      out.write("    \n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/hotel/hotel_list.jsp(30,6) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../common/menubar.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }
}
