/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-11-03 16:31:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.travel;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class travelList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1604145899265L));
    _jspx_dependants.put("jar:file:/C:/Users/Joy/git/Spring-Project-Trip2Reap/Spring-Final-Trip2Reap/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" href=\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/travel/travelList.css\"/>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("<section>\n");
      out.write("\t<header>\n");
      out.write("   \t ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t</header>\n");
      out.write("\t<div id=\"all_div\">\n");
      out.write("\t\t<div id=\"menu_div\">\n");
      out.write("\t\t\t<div id=\"menu_left_div\">\n");
      out.write("\t\t\t\t<!-- <img src=\" ../../../images/여행지아이콘.png\" id=\"menu_img\"/> -->\n");
      out.write("\t\t\t\t<img src=\"resources/images/travel.png\" id=\"menu_img\"/>\n");
      out.write("\t\t\t\t<span id=\"menu\">여행지</span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"menu_right_div\">\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"input_search\"/>\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"검색\" id=\"button_search\"/>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- 해쉬태그 카테고리 -->\n");
      out.write("\t\t<div id=\"hashtag_div\">\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<a href=\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/travel/travelList.jsp\">#전체</a>&nbsp;&nbsp;\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<a href=\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/travel/travelList.jsp\">#문화시설</a>&nbsp;&nbsp;\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<a href=\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/travel/travelList.jsp\">#레포츠</a>&nbsp;&nbsp;\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<a href=\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/travel/travelList.jsp\">#쇼핑</a>&nbsp;&nbsp;\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<a href=\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/travel/travelList.jsp\">#자연</a>&nbsp;&nbsp;\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<a href=\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/travel/travelList.jsp\">#축제</a>&nbsp;&nbsp;\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- 지역/테마 카테고리 -->\n");
      out.write("\t\t<div id=\"cate_table_div\">\n");
      out.write("\t\t\t<span id=\"cate_name\">지역</span>\n");
      out.write("\t\t\t\t<span id=\"cate_icon\"><i class=\"fas fa-leaf\" style=\"height:13px;, width:13px; color:#a7e1af;\"></i></span>\n");
      out.write("\t\t\t\t<table id=\"local_table\">\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>전체</td>\n");
      out.write("\t\t\t\t\t\t<td>서울</td>\n");
      out.write("\t\t\t\t\t\t<td>인천</td>\n");
      out.write("\t\t\t\t\t\t<td>대전</td>\n");
      out.write("\t\t\t\t\t\t<td>대구</td>\n");
      out.write("\t\t\t\t\t\t<td>광주</td>\n");
      out.write("\t\t\t\t\t\t<td>부산</td>\n");
      out.write("\t\t\t\t\t\t<td>울산</td>\n");
      out.write("\t\t\t\t\t\t<td>세종</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>경기</td>\n");
      out.write("\t\t\t\t\t\t<td>강원</td>\n");
      out.write("\t\t\t\t\t\t<td>충북</td>\n");
      out.write("\t\t\t\t\t\t<td>충남</td>\n");
      out.write("\t\t\t\t\t\t<td>경북</td>\n");
      out.write("\t\t\t\t\t\t<td>경남</td>\n");
      out.write("\t\t\t\t\t\t<td>전북</td>\n");
      out.write("\t\t\t\t\t\t<td>전남</td>\n");
      out.write("\t\t\t\t\t\t<td>제주</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<span id=\"cate_name\">테마</span>\n");
      out.write("\t\t\t\t<span id=\"cate_icon\"><i class=\"fas fa-leaf\" style=\"height:13px;, width:13px; color:#a7e1af;\"></i></span>\n");
      out.write("\t\t\t\t<table id=\"theme_table\">\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>전체</td>\n");
      out.write("\t\t\t\t\t\t<td>관광지</td>\n");
      out.write("\t\t\t\t\t\t<td>음식점</td>\n");
      out.write("\t\t\t\t\t\t<td>명소</td>\n");
      out.write("\t\t\t\t\t\t<td>축제</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div id=\"list_all_div\">\n");
      out.write("\t\t\t<div id=\"list_count_div\">\n");
      out.write("\t\t\t\t총<span id=\"list_count\">76</span>건\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- 여행지 div -->\n");
      out.write("\t\t\t<div id=\"list_travel_div\">\n");
      out.write("\t\t\t\t<div id=\"travel_img_div\">\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/송도.JPG\" id=\"travel_img\"/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"travel_name_writer_div\">\n");
      out.write("\t\t\t\t\t<div id=\"travel_name\">송도 센트럴파크</div>\n");
      out.write("\t\t\t\t\t<div id=\"travel_writer\">인천 송도</div>\n");
      out.write("\t\t\t\t\t<div id=\"travel_tag\">#레포츠 #가족과함께 #자연</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<span id=\"list_etc\"><i class=\"fas fa-ellipsis-h\" style=\"width:30px; height:30px; font-weight: 1px;\"></i></span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<br><br>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div id=\"list_travel_div\">\n");
      out.write("\t\t\t\t<div id=\"travel_img_div\">\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/송도.JPG\" id=\"travel_img\"/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"travel_name_writer_div\">\n");
      out.write("\t\t\t\t\t<div id=\"travel_name\">송도 센트럴파크</div>\n");
      out.write("\t\t\t\t\t<div id=\"travel_writer\">인천 송도</div>\n");
      out.write("\t\t\t\t\t<div id=\"travel_tag\">#공원 #가족과함께 #자연</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<span id=\"list_etc\"><i class=\"fas fa-ellipsis-h\" style=\"width:30px; height:30px; font-weight: 1px;\"></i></span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<br><br>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div id=\"list_travel_div\">\n");
      out.write("\t\t\t\t<div id=\"travel_img_div\">\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/송도.JPG\" id=\"travel_img\"/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"travel_name_writer_div\">\n");
      out.write("\t\t\t\t\t<div id=\"travel_name\">송도 센트럴파크</div>\n");
      out.write("\t\t\t\t\t<div id=\"travel_writer\">인천 송도</div>\n");
      out.write("\t\t\t\t\t<div id=\"travel_tag\">#공원 #가족과함께 #자연</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<span id=\"list_etc\"><i class=\"fas fa-ellipsis-h\" style=\"width:30px; height:30px; font-weight: 1px;\"></i></span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<br><br>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t<div id=\"list_travel_div\">\n");
      out.write("\t\t\t\t<div id=\"travel_img_div\">\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/송도.JPG\" id=\"travel_img\"/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"travel_name_writer_div\">\n");
      out.write("\t\t\t\t\t<div id=\"travel_name\">송도 센트럴파크</div>\n");
      out.write("\t\t\t\t\t<div id=\"travel_writer\">인천 송도</div>\n");
      out.write("\t\t\t\t\t<div id=\"travel_tag\">#관광지 #미세먼지x #식물원</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<span id=\"list_etc\"><i class=\"fas fa-ellipsis-h\" style=\"width:30px; height:30px; font-weight: 1px;\"></i></span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t</div><!-- 전체 div끝 -->\n");
      out.write("\t\n");
      out.write("</section>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/travel/travelList.jsp(13,5) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../common/menubar.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }
}
